# Generated by Django 4.0.3 on 2022-05-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratraweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='Pan_no',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='massage',
        ),
    ]
